CREATE TABLE conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(16) NOT NULL,
    name VARCHAR(100),
    direct_key VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_conversations_type CHECK (type IN ('DIRECT', 'GROUP')),
    CONSTRAINT uk_conversations_direct_key UNIQUE (direct_key)
);

CREATE INDEX idx_conversations_updated_at ON conversations (updated_at DESC);

CREATE TABLE conversation_members (
    conversation_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT fk_conversation_members_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_conversation_members_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_conversation_members_user ON conversation_members (user_id, conversation_id);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INTEGER NOT NULL,
    sender_id INTEGER NOT NULL,
    body VARCHAR(4000) NOT NULL,
    client_message_id UUID,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT ck_messages_body_not_blank CHECK (length(btrim(body)) BETWEEN 1 AND 4000),
    CONSTRAINT uk_messages_idempotency UNIQUE (conversation_id, sender_id, client_message_id)
);

CREATE INDEX idx_messages_conversation_created ON messages (conversation_id, created_at DESC, id DESC);
